"""Central asset aliases and lightweight metadata for runtime UI images."""

ASSETS = {
    "bg_stage": "xingbao_v3/backgrounds/bg_stage_space.png",
    "bg_main": "backgrounds/space_console_bg.png",
    "bg_home": "backgrounds/home_stage.png",
    "bg_game": "backgrounds/game_stage.png",
    "bg_report": "backgrounds/report_stage.png",
    "xingbao_normal": "characters/orb/xingbao_orb_normal.png",
    "xingbao_happy": "characters/orb/xingbao_orb_happy.png",
    "xingbao_thinking": "characters/orb/xingbao_orb_thinking.png",
    "xingbao_encouraging": "characters/orb/xingbao_orb_encouraging.png",
    "panel_glass": "ui/glass_panel.png",
    "panel_glass_active": "ui/glass_panel_active.png",
    "mission_card": "ui/mission_card.png",
    "mission_card_active": "ui/mission_card_active.png",
    "button_primary": "ui/button_primary.png",
    "button_secondary": "ui/button_secondary.png",
    "feedback_success": "ui/feedback/success_banner_green.png",
    "feedback_info": "ui/feedback/water_banner_blue.png",
    "feedback_warning": "ui/feedback/heart_banner_pink.png",
    "reward_status_bar": "ui/feedback/reward_status_bar.png",
    "icon_color": "icons/mission/color_energy.png",
    "icon_geometry": "icons/mission/geometry_signal.png",
    "icon_memory": "icons/mission/memory_route.png",
    "icon_star": "icons/mission/star_reward.png",
    "icon_energy": "icons/mission/energy_core.png",
    "icon_back": "icons/system/back_arrow_large.png",
    "icon_touch": "icons/system/touch_pointer.png",
    "icon_report": "icons/system/record_report.png",
    "shape_circle": "icons/shapes/neon_circle_large.png",
    "shape_square": "icons/shapes/neon_square_large.png",
    "shape_triangle": "icons/shapes/neon_triangle_large.png",
    "shape_star": "icons/shapes/neon_star_large.png",
    "shape_heart": "icons/shapes/neon_heart_large.png",
    "shape_rectangle": "xingbao_v3/icon_set/shape_rectangle_ellipse_atlas.png",
    "shape_ellipse": "xingbao_v3/icon_set/shape_rectangle_ellipse_atlas.png",
    "color_red": "icons/color_red.png",
    "color_yellow": "icons/color_yellow.png",
    "color_blue": "icons/color_blue.png",
    "color_green": "icons/color_green.png",
    "color_purple": "icons/color_purple.png",
    "color_orange": "icons/color_orange.png",
    "energy_red": "xingbao_v3/energy_orbs/energy_red.png",
    "energy_yellow": "xingbao_v3/energy_orbs/energy_yellow.png",
    "energy_blue": "xingbao_v3/energy_orbs/energy_blue.png",
    "energy_green": "xingbao_v3/energy_orbs/energy_green.png",
    "energy_purple": "xingbao_v3/energy_orbs/energy_purple.png",
    "energy_orange": "xingbao_v3/energy_orbs/energy_orange.png",
    "icon_color_energy": "xingbao_v3/icon_set/icon_color_energy.png",
    "icon_geometry_signal": "xingbao_v3/icon_set/icon_geometry_signal.png",
    "icon_memory_route": "xingbao_v3/icon_set/icon_memory_route.png",
    "icon_star_reward": "xingbao_v3/icon_set/icon_star_reward.png",
    "icon_energy_core": "xingbao_v3/icon_set/icon_energy_core.png",
    "icon_touch_interaction": "xingbao_v3/icon_set/icon_touch_interaction.png",
    "icon_ai_companion": "xingbao_v3/icon_set/icon_ai_companion.png",
    "panel_companion": "xingbao_v3/panels/panel_companion_side.png",
    "panel_top_task": "xingbao_v3/panels/panel_top_task.png",
    "panel_feedback": "xingbao_v3/panels/panel_feedback.png",
    "panel_mission_card": "xingbao_v3/panels/panel_mission_card.png",
    "panel_header_bar": "xingbao_v3/panels/panel_compact_header_bar.png",
    "panel_energy_bar": "xingbao_v3/panels/panel_energy_bar.png",
    "chip_local": "xingbao_v3/ui_controls/status_chips/status_local.png",
    "chip_touch": "xingbao_v3/ui_controls/status_chips/status_touch.png",
    "chip_safe": "xingbao_v3/ui_controls/status_chips/status_safe.png",
    "chip_ready": "xingbao_v3/ui_controls/status_chips/status_ready.png",
    "select_blue": "xingbao_v3/ui_controls/select_chips/chip_select_blue_1.png",
    "select_purple": "xingbao_v3/ui_controls/select_chips/chip_select_purple_1.png",
    "select_yellow": "xingbao_v3/ui_controls/select_chips/chip_select_yellow_1.png",
    "back_arrow": "xingbao_v3/ui_controls/back_arrows/back_round_blue.png",
    "progress_0_100": "xingbao_v3/ui_controls/progress_pills/progress_0_100.png",
    "card_state_normal": "xingbao_v3/state_cards/card_state_normal.png",
    "card_state_hover": "xingbao_v3/state_cards/card_state_hover.png",
    "card_state_selected": "xingbao_v3/state_cards/card_state_selected.png",
    "card_state_correct": "xingbao_v3/state_cards/card_state_correct.png",
    "card_state_incorrect": "xingbao_v3/state_cards/card_state_incorrect.png",
    "button_confirm": "xingbao_v3/ui_controls/compact_buttons/btn_confirm.png",
    "button_home": "xingbao_v3/ui_controls/compact_buttons/btn_home.png",
    "icon_counting_planet": "xingbao_v3/icon_set/icon_counting_planet.png",
    "icon_habit_match": "xingbao_v3/icon_set/icon_habit_match.png",
    "icon_skill_focus": "xingbao_v3/icon_set/icon_skill_focus.png",
    "icon_english_words": "xingbao_v3/icon_set/icon_english_words.png",
    "count_star": "xingbao_v3/counting/count_star.png",
    "count_planet": "xingbao_v3/counting/count_planet.png",
    "count_apple": "xingbao_v3/counting/count_apple.png",
    "count_banana": "xingbao_v3/counting/count_banana.png",
    "habit_toothbrush": "xingbao_v3/habits/habit_toothbrush.png",
    "habit_brush_teeth": "xingbao_v3/habits/habit_brush_teeth.png",
    "habit_hand": "xingbao_v3/habits/habit_hand.png",
    "habit_wash_hands": "xingbao_v3/habits/habit_wash_hands.png",
    "habit_bed": "xingbao_v3/habits/habit_bed.png",
    "habit_sleep": "xingbao_v3/habits/habit_sleep.png",
    "habit_book": "xingbao_v3/habits/habit_book.png",
    "habit_read": "xingbao_v3/habits/habit_read.png",
    "habit_spoon": "xingbao_v3/habits/habit_spoon.png",
    "habit_eat": "xingbao_v3/habits/habit_eat.png",
    "xingbao_idle_01": "xingbao_v3/xingbao_anim/xingbao_idle_01.png",
    "xingbao_idle_02": "xingbao_v3/xingbao_anim/xingbao_idle_02.png",
    "xingbao_idle_03": "xingbao_v3/xingbao_anim/xingbao_idle_03.png",
    "xingbao_idle_04": "xingbao_v3/xingbao_anim/xingbao_idle_04.png",
    "xingbao_happy_01": "xingbao_v3/xingbao_anim/xingbao_happy_01.png",
    "xingbao_happy_02": "xingbao_v3/xingbao_anim/xingbao_happy_02.png",
    "xingbao_happy_03": "xingbao_v3/xingbao_anim/xingbao_happy_03.png",
    "xingbao_thinking_01": "xingbao_v3/xingbao_anim/xingbao_thinking_01.png",
    "xingbao_thinking_02": "xingbao_v3/xingbao_anim/xingbao_thinking_02.png",
    "xingbao_thinking_03": "xingbao_v3/xingbao_anim/xingbao_thinking_03.png",
    "xingbao_encourage_01": "xingbao_v3/xingbao_anim/xingbao_encourage_01.png",
    "xingbao_encourage_02": "xingbao_v3/xingbao_anim/xingbao_encourage_02.png",
    "xingbao_encourage_03": "xingbao_v3/xingbao_anim/xingbao_encourage_03.png",
    "xingbao_celebrate_01": "xingbao_v3/xingbao_anim/xingbao_celebrate_01.png",
    "xingbao_celebrate_02": "xingbao_v3/xingbao_anim/xingbao_celebrate_02.png",
    "xingbao_celebrate_03": "xingbao_v3/xingbao_anim/xingbao_celebrate_03.png",
    "xingbao_celebrate_04": "xingbao_v3/xingbao_anim/xingbao_celebrate_04.png",
}

ASSET_META = {
    "xingbao_normal": {"crop": (118, 0, 518, 398)},
    "xingbao_happy": {"crop": (118, 0, 518, 398)},
    "xingbao_thinking": {"crop": (118, 0, 518, 398)},
    "xingbao_encouraging": {"crop": (118, 0, 518, 398)},
    "shape_rectangle": {"crop": (125, 180, 370, 320), "remove_dark_background": True},
    "shape_ellipse": {"crop": (595, 178, 865, 320), "remove_dark_background": True},
}
