from enum import Enum


class AppState(str, Enum):
    HOME = "HOME"
    DIFFICULTY_SELECT = "DIFFICULTY_SELECT"
    SKILL_CARD = "SKILL_CARD"
    GAME_RUNNING = "GAME_RUNNING"
    GAME_FEEDBACK = "GAME_FEEDBACK"
    GAME_SUMMARY = "GAME_SUMMARY"
    TODAY_RECORD = "TODAY_RECORD"
    WEEKLY_RECORD = "WEEKLY_RECORD"
    DEMO_MODE = "DEMO_MODE"
    EXIT = "EXIT"
